- run.sh
Created a run script using uvicorn, which should make it easier to run the API on your local port. 
Arthur Yang
Cole Richards
Dan Kositzke
Kateryna Pasechnyk
Kevin Lynner
Matt Clibanoff
Nigel Clinton
Viet Huynh
Xianshi Wei
https://www.loom.com/share/59cfbe747c8346ccb0b72a8791c6f8d8
> Adds run script

- .ebignore
Updates the `.ebignore` file such that all unneeded files are properly ignored at deployment time.
> updates the ebignore file

- app/api.py
- app/data.py
Added function to have the database report what tables it has and how many entries there are in each of those tables.
[Loom](https://www.loom.com/share/079ce2f61a2747038da4c21ce651771e)
- [*] New feature
- [*] This change requires a documentation update
- [ *] My code follows PEP8 style guide
- [ *] I have removed unnecessary print statements from my code
- [ *] I have made corresponding changes to the documentation if necessary
- [ *] My changes generate no errors
- [ *] No commented-out code
- [ *] Size of pull request kept to a minimum
- [ *] Pull request description clearly describes changes made & motivations for said changes
> Added function

- app/data.py
- requirements.txt
Fixes intermittent bug in connection script for Mongo. 
Installs and imports certifi module, adds tlsCAFile(Transport Layer Security Certificate Authority) to solve "invalid certificate" issue when connecting to MongoDB Atlas Database.
document change: 
adds certifi~=2021.10.8 in requirements.txt
bug fix:
in data.py, imports certifi module, and adds tlsCAFile=certifi.where() in MongoClient function: MongoClient(getenv("MONGO_URL"), tlsCAFile=certifi.where()) 
> Bug fix - intermittent bug in connection script for Mongo

- app/vader_sentiment.py
Adds sentiment analysis with `vaderSentiment`.
[quick walkthrough](https://www.loom.com/share/5cfcf5693afb40818aa1f2c9efbbd22c)
> adds a vader sentiment analyzer function

- .gitignore
- notebooks/Generating_Mock_Review_Data.ipynb
- notebooks/review.csv
- As a data scientist, I want to have mock review data, so that I can perform sentiment analysis
- Generating Mock Reviews Data with data frame containing mentor_id, mentee_id and reviews.
https://www.loom.com/share/4617146518aa48289d8de31de42c78f7
- Added Loom video in the description
BhavaniLakshmi Annapurna Jagarlamudi
Archana Coimbatore Sivagurunathan
> Generating Mock Reviews Data

- app/api.py
- app/data.py
- app/model.py
- data_generators/data_options.py
- data_generators/random_match.py
- data_generators/user_generators.py
Updates to the model were made to improve results of matching algorithm. Sorting now considers pair programming desire and industry knowledge, in addition to experience level and subject. 
Several variable names were changed to have consistency with the Underdog Devs backend (mentee_id -> profile_id, user_id -> profile_id).
_connect for MongoDB class is more internal functionality. A get_collection method was added to replace the flexibility _connect had.
Data Generator scripts now create more complete Mentors and Mentee data. UUID format is used to generate `profile_id`.
Fixes # [Trello issue](https://trello.com/c/TnuU2T9f)
[Explanation video](https://www.loom.com/share/2d4fa669e03b4d5e825d9f83a39fe7fe)
Contributors: @BrokenShell @ulloa @ev-horrosh @LynnerKevin @RylandGomez @mktran0417 …
> Updated ML Model and MongoDB Class

- notebooks/calendly_research.ipynb
Calendy API research to see what data is available
[quick video](https://www.loom.com/share/0c45ba469c4e4c91b83f8d2dee5e9720)
contributors: @archana062031 @Annapurnaj91 @mktran0417 
[trello card](https://trello.com/c/2xCnlYNQ)
> add calendly research notebook

- app/data.py
Fix IndentationError: unexpected indent found in data.py.
Chunyan "Christine" Wang
SirivennelaVempati
> fix indent bugs in data.py

- data_generators/user_generators.py
There was some important code that commented out by myself. I went back in and uncommented it.
Loom: https://www.loom.com/share/18f6ec200f9c45a7925a5d38d4b11c76
> Uncommented code that was left commented on accident.

- data_generators/user_generators.py
This was an update to the Meeting Class to further conform to the backend schema and promote easier readability.
Loom video: https://www.loom.com/share/033654af03f541fa839d24144175c1cf
> Updated Meeting Class to match backend schema

- app/api.py
- app/utilities.py
Co-Authored-By: Yefim Gorodnitskiy <ygorodnitskiy@gmail.com>
Co-Authored-By: Jonathan McGraw <24931398+jonathan-mcgraw@users.noreply.github.com>
Co-Authored-By: Nicholas Papenburg <60982660+NPAPENBURG@users.noreply.github.com>
Co-Authored-By: TedKim <tedkimemail@yahoo.com>
Co-Authored-By: Maxwell Johnson <86576382+WaylayOvercast@users.noreply.github.com>
We created a custom endpoint where the functionality will be implemented at a later date.
Loom video:
https://www.loom.com/share/29e5bddfe87b4046a0f92dff6176538b
> Financial Aid Custom Endpoint

- app/api.py
Co-Authored-By: Matt Grohnke <m.grohnke@gmail.com>
The Data Science api functionality was updated and merged, but the api version numbering was not updated along with the code change. 
Incremented ds api version from 0.44.1 to 0.44.2.
Also cleaned up docstring in 'financial_aid' function (removing duplicated "the" strings).
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
- [x ] My code follows PEP8 style guide
- [x ] I have removed unnecessary print statements from my code
- [x ] I have made corresponding changes to the documentation if necessary
- [x ] My changes generate no errors
- x[ ] No …
> Incremented api version # to 0.44.2

- notebooks/Underdogs_Meeting_Sentiment.ipynb
Added a visualization to the underdog_meeting_sentiment.ipynb file to enhance visibility and communicability to users.
Co-Authored by :
@hollberg 
@MichaelJP-DS 
@Zack-Quintana 
TPM's:
@BrittniKarat 
@itsmerobert12 
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
> Added Visualizations to .ipynb file

- notebooks/NLTK_Application_Scanner.ipynb
Using NLP with 
- NLTK
- Count Vectorizer
- Fit Transform
- Cosine Similarity
And the Custom Cleaning Function: 
- Takes in a variable with a multiline string inside
- Removes all numbers 
- Changes all uppercase to lowercase
- Strips the spaces, tabs, and newlines from the front and back
- Takes out email addresses
- Takes out all punctuation
- Separates the words
- Deletes stop words
- Uses lemmatization to get the root word
This feature takes a job description and compares it to a resume. It returns a percentage of how much your resume matches the job description. 
We compared: 
- Two data science resumes to a bakery job
- Two data science resumes to a data science job
- The bakery job to the bakery job
- The data science job to the data science job
The results of the bakery job …
> NLTK Application Scanner

- app/api.py
Created Endpoints for Mentors and Mentees to check their data, in this case using a "read" endpoint, given specific queries.
This was made in conjunction with Create and Update so that users could submit their information, check if it needs updates, and of course update it accordingly.
[X ] New feature
- [X ] My code follows PEP8 style guide
- [X ] I have removed unnecessary print statements from my code
- [X ] I have made corresponding changes to the documentation if necessary
- [X ] My changes generate no errors
- [X ] No commented-out code
- [X ] Size of pull request kept to a minimum
- [X ] Pull request description clearly describes changes made & motivations for said changes
My Loom Video: https://www.loom.com/share/4129501ebea2429e8495c0cb7764c56f
> Created Endpoints for Mentor and Mentee Read

- app/api.py
Reverts BloomTech-Labs/underdog-devs-ds-a#116
> Revert "Created Endpoints for Mentor and Mentee Read"

- app/api.py
Allows getting the password from a local setup, but not deployed API
> setup password update

- app/computer_assignment.py
- app/schema.py
- app/utilities.py
- app/vader_sentiment.py
- data_generators/job_description_scraper.py
- requirements.txt
- test_coverage/api_testing.py
- test_coverage/fastapi_testing.py
This Branch is just a small clean up of the DS code base to meet PEP8 standards on most .py files. 
Changes made were contained in the /app and  /data_generators folders. 
Added TODO calls for bug Fix branches in the future. 
[Loom Link](https://www.loom.com/share/01537f00de7b47d1b3bac56f2c4715e6)
> Code clean up/pep8 clean up

- app/model.py
- data_generators/user_generators.py
Updated the Mentee and Mentor classes in the user_generator.py file to match the updated schema.py file 
Loom Link: https://www.loom.com/share/49e3e97f2e234c19b917d97180389870
> Added changes to the classes Mentor and Mentee user generator

- notebooks/Adzuna_Jobs_Board_API_Demo.ipynb
Looked into a job board called Adzuna with a free API that we could potentially use to compile job listings. The notebook contains requests to some of the endpoints, mainly the one for searching the Adzuna job database
> notebook exploring free Adzuna job board API

- app/schema.py
- data_generators/user_generators.py
- requirements.txt
Updates Mentee BaseModel and UpdateModel to match web schema (partially). Some changes need to be done on the web side for everything to line up properly. 
Adds email validation through Pydantic, which required a small change to the import statement for Pydantic in the requirements.txt file. Adds code to forbid "extra" fields in Mentors and Mentees.
Removes some dead code.
Partially Fixes the schema mismatch between Web and DS API.
> Updates Mentee BaseModel and UpdateModel to match web schema

- app/api.py
- app/schema.py
Updated Mentor Schema, changed "commitment" value to boolean. 
Updated API version 
https://www.loom.com/share/cdbd53b816dd4aeb92c0d644cba95a82
> Mentor schema "commitment" update. API version update

- app/model.py
Updates to the MatcherSortSearch Class:
-  Removed unused random import (sample)
-  Removed mentee industry knowledge 
-  Changed mentor industry knowledge to not mentor industry knowledge for sorting
https://www.loom.com/share/f1e948d670a449fe90e1cc8557895b6a
> Matcher update

- app/schema.py
- data_generators/user_generators.py
After a meeting with the team, we concluded both the Mentor and Mentee forms required validation, so I have added "validate_status" to Mentor, UpdateMentor and RandomMentor classes. 
https://www.loom.com/share/167d764d177e403cabfb997dce9d0ed6
> Mentor schema update - validation

- app/schema.py
Co-authors: Jason Gersing, Willis Bridges, Cristian Ibarra-Villegas, Martha Gonzalez 
Copied schema format from Postgres tables for use in schema.py. Due to [redundant data](https://docs.google.com/spreadsheets/d/1oN_fJCTZVBwMbRVW-fHmRadpX0RlCMt4a0J-M7qUN88/edit?usp=sharing) stored in MongoDB and Postgres,
we've decided to migrate to MongoDB for the bulk of data storage and handling. This PR is a first step in that elaborate process.
Fixes # [BL-450](https://bloomtechlabs.atlassian.net/browse/BL-450?atlOrigin=eyJpIjoiZDJkMzUwYWU1ZDAyNGE2N2EwZGE5ZTNlNmQ0YWFiYjUiLCJwIjoiaiJ9)
Team C -- tables transferred: Notes, Comments, Mentee_Progression
https://www.loom.com/share/24d1f4e113fe491e86240caaa3b4ab72
> BL-450 - (2/3) Schema from Postgres tables mirrored in schema.py - Team C

- app/schema.py
Co-authors: Jason Gersing, Cristian Ibarra-Villegas, Martha Gonzalez
Mentor collection update. Part of overarching plan to redo Database architecture to capture desired data with additional fields. For visibility, check this [excel spreadsheet](https://docs.google.com/spreadsheets/d/1dt54x0OVqgNfmGfW_omdQtEu6NXPfMZz_DUQKR7HCXo/edit?usp=sharing) (specifically the Refactor Final Draft tab) to see our high-level plans for refactoring each table.
Compiled new fields to Mentor class for architectural overhaul.
LOOM:
https://www.loom.com/share/43c4ec60203b40feb7ddc535ee76a4e6
> BL- 488 Feature/mentor model update

- data_generators/user_generators.py
Co-authors: Jason Gersing, Willis Bridges, Martha Gonzalez
Updates RandomMentor class in user_generators.py to match the latest schema. Part of the overarching plan to redo Database architecture to capture desired data with additional fields. Added new attributes as necessary and ensured attribute data types met revised schema requirements.
Fixes BL-488 (subtask BL-496)
[loom](https://www.loom.com/share/195790c3e4a047959af6353e34d0a940)
> BL-488 Feature/mentor generator update

- app/analysis.py
- app/api.py
- app/computer_assignment.py
- app/data.py
- app/graphs.py
- app/utilities.py
Deletes several outdated endpoints. We worked on this as a team in Workshop.
> deletes some dead code, bumps the api version

- app/api.py
- app/schema.py
We created CRUD functions for the feedback class and modified the existing Feedback Schema in the Schema.py file to handle new data. 
READ: This function takes mentee_id, mentor_id, ticket_id, or None as arguments. Given mentee_id it will return all feedback for that mentee. Given mentor_id it will return all feedback for that mentor. Given ticket_id it will return the ticket with that ID. Given None, it will read all tickets.
CREATE: This function takes data in the format of the feedback schema. The arguments are Text, Ticket_id, mentee_id, mentor_id, DateTime, and vader_score. The Datetime, Ticket_id, and vader_score are all automatically generated upon submission of the ticket. The only fields you need to input are text, mentee_id, and mentor_id.
DELETE: This function takes ticket_id …
> BL-507 DS Feedback CRUD functions and Schema changes 

- app/schema.py
- data_generators/generators.py
Co-authors: Kristina Cernekova, Sujata Sahoo, Roger Vieira
Meeting collection schema updated to match the plan for restructuring the DS database.
[Loom video](https://www.loom.com/share/79d8b511dd3c472fa444e36237373ef7)
> BL-586 Feature/meeting schema update

- data_generators/generators.py
Co-authors: Kristina Cernekova, Sujata Sahoo, Roger Vieira
Update the Meetings generator to reflect the changes made in the Meetings schema.
[Loom video](https://www.loom.com/share/7290cad79afc45deb89e0d24bcc272bb)
> BL-587 Feature/update meeting generator

- data_generators/data_options.py
Implemented a more streamlined random datetime generator with a single import line. Fixed an earlier PR issue that had a merge conflict.
> Implemented random datetime generator - ticket BL-681

- app/schema.py
- Removed MentorIntake and Resource from schema.py
- Removed updated_at field in Mentor, Mentee, MentorUpdate, and MenteeUpdate
- Changed 'heard_about' in Mentee and MenteeUpdate to 'referred_by' to match Mentor collection.
> BL-588 Feature/schema cleanup update

- LICENSE
Small change to update the LICENSE file
> updates LICENSE file

- requirements.txt
- run.sh
- Updates the requirement.txt file to include `testresources==2.0.1`
- Updates the `run.sh` file to target uvicorn installed in the venv - not the system PATH
> Linux compatibility requirements

- data_generators/generators.py
- data_generators/seeds.py
- test_coverage/schema_validation_testing.py
We've added a testing file that checks our random generators against our validation schema. This test is called in the seeds file, so that if one test fails, the entire seeding process stops. 
We've used simple assert statements to test these classes. 
[LOOM VID x1000](https://www.loom.com/share/6bd8f27dd8114416bad65b4f4d52a77c)
> BL-683/Random-Generator-Validation

- README.md
Removed broken Python badge and replaced it with a working badge.
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
> Fixed broken Python badge in README.md

- app/model.py
Updated MatcherSortSearch class within model.py to account for 3 relevant fields:
*   1.) "is_active" == type(bool) whether or not mentee or mentor have active accounts.
*   2.) "accepting_new_mentees" == type(bool) whether or not mentor is currently taking on new mentees. 
*   3.) "validate_status" == type(str) application status classified as one of ["approved", "rejected", "pending"]
[BL-729 Jira Ticket](https://bloomtechlabs.atlassian.net/browse/BL-729)
[Steven's LoomTech Talk](https://www.loom.com/share/b99f8081e5e647b5ae1bcf67c1643545)
> BL-729 Updated Matcher Algorithm

- README.md
Updated DS README file to include all contributors. Motivation was to give credit to those who have contributed to this project. 
Fixes # (BL-799)
Loom Video 
https://www.loom.com/share/809ea213d12242e0890e880fb84ec8e1
> Updates contribution section for DS readme.md file

- data_generators/generators.py
Implements linear choice for generating sophisticated mock data.
- Front: values at the front of the collection are more common
- Middle: values at the middle of the collection are more common
- Back: values at the back of the collection are more common
[Workshop Video Link](https://youtu.be/TbBpQQcBYkI)
> implements linear choice for generating sophisticated mock data

- app/data.py
- data_generators/generators.py
- requirements.txt
The ticket called for RandomMenteeFeedback to run the vader score on the text. So, that was added. Also removed the indexing of the random choice call "[:800]". Please advise. Thank you!
https://bloomtechlabs.atlassian.net/browse/BL-748
https://www.loom.com/share/01119e64da664481a3cc9e4c7b2e9630
> BL-748 DS feedback generator update

- app/routers/feedback_router.py
These docs got deleted  somehow. All better now!
Special thanks to Jonathan for retrieving them from the deleted GH branch.
Contributors:
Jonathan Torres
Komila Mirolimova
> updates feedback router to include docs

- app/schema.py
- data_generators/data_options.py
- data_generators/generators.py
We paid off our tech debt!
- There were some functions in data_options.py -- moved those to generators.py
- Abstracted away repetition in schema.py with Inheritance from ExtraForbid class 
- Got rid of the import * in generator file, added the appropriate individual imports
[Jira Ticket](https://bloomtechlabs.atlassian.net/browse/BL-940?atlOrigin=eyJpIjoiNDg5M2I4ZWVjYTVjNDkxNWFjMGUzODRhYmIyMTM3MTMiLCJwIjoiaiJ9)
> BL-940-ds-refactoring-paying-off-some-tech-debt

- app/graphs.py
- app/routers/graph_router.py
We added a descriptive paragraph for the tech stack by role visualization.
[Jira Ticket.](https://bloomtechlabs.atlassian.net/browse/BL-962?atlOrigin=eyJpIjoiMjk0NTA3NjVkZWMyNGMyYmE3OTRmOWZkZTNiODM5Y2IiLCJwIjoiaiJ9)
[Loom video](https://www.loom.com/share/73af376d0d2b4d9ebe3bc8868a413ecc)
[Loom video update](https://www.loom.com/share/786de2afe121480a8ea6ad2ded41a420)
> BL-962_descriptive_Paragraphs_for_visualizations

- app/schema.py
- data_generators/generators.py
- tests/schema_validation.py
- Replaces all `generate_uuid(16)` calls with `uuid.uuid4()` random uuid generator call
- Sets `app/schema.py` max_length constraints to 36 for relevant id fields.
- Removes `generate_uuid` function and orphaned imports
[BL-841](https://bloomtechlabs.atlassian.net/browse/BL-841)
[Loom Video](https://www.loom.com/share/48e593f559c249a9b71f1fa042cfcdfe)
> Bl 841 ds update how we generate uui ds

- requirements.txt
Please include a detailed summary.
https://bloomtechlabs.atlassian.net/jira/software/c/projects/BL/boards/10?modal=detail&selectedIssue=BL-1026
- [x ] Bug fix
- [] New feature
- [ X] My code follows PEP8 style guide
- [ X] I have removed unnecessary print statements from my code
- [ x] I have made corresponding changes to the documentation if necessary
- [ x] My changes generate no errors
- [ x] No commented-out code
- [ x] Size of pull request kept to a minimum
- [ x] Pull request description clearly describes changes made & motivations for said changes
Changes too small to create a loom video
> Added certifi library to requirements.txt

- data_generators/data_options.py
Remove unnecessary imports from the helper file, because helper doesn't use these modules.
https://bloomtechlabs.atlassian.net/browse/BL-1039
Changes too small to make a loom video.
> Remove unnecessary imports

- app/routers/match_router.py
- data_generators/generators.py
- data_generators/seeds.py
I have added a mock data generator for matches to the seeds script.
A mock Data generates from previously generated Mentees and Mentors. It randomly takes 20 mentors ids and for each of them add random number of mentees ids.
When the database is reseeded all IDs will changed to random IDs, be aware of this.
Please include a link to the associated Jira Ticket.
https://bloomtechlabs.atlassian.net/browse/BL-1038?atlOrigin=eyJpIjoiZWQ1N2MxNGM2OWRlNGQxZThiZTU0ZjAyMTRkODQzZTgiLCJwIjoiaiJ9
https://www.loom.com/share/2724ccf1b5eb4031819ebdb76835c591
> Bl 1038 ds need to add matches to data generators

- app/graphs.py
- app/routers/graph_router.py
Reduce number of graphing functions to one, reuse this function for all graphing endpoints.
graphs.py contained multiple similar functions, now reduced to a single function with minor changes to allow a different figure title to be passed at each endpoint.
Changes to graph_router.py: Use the single graphing function at each endpoint and pass a descriptive title string as argument, per function changes in graphs.py.
The screenshot below is from the stacked bar chart notebook with the changes implemented in graphs.py, which should show how the graph will appear.
[Jira Ticket](https://bloomtechlabs.atlassian.net/jira/software/c/projects/BL/boards/10?modal=detail&selectedIssue=BL-1046&search=ds).
[Loom link](https://www.loom.com/share/e36c5c1f846142329268b78684cb83da)
> BL-1046-ds-bug-in-graph-router-py
